name: GitHub Pages

on:
  push:
    branches: [none]
  # pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: 🚚 Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rulex-play/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 🔧 Build rulex WASM
        working-directory: ./rulex-play
        run: wasm-pack build --target web

      - name: 🚚 Install dependencies
        run: npm ci

      - name: 📦 Build production website
        run: npm run build -- -v

      - name: List files in /public
        run: ls public

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./public
